#!/usr/bin/env python3
"""p-Adic orbit-Cantor intersection analysis for the Erdős Ternary Conjecture.

Computes the intersection of the ×2 orbit in Z_3 with the Cantor set Σ_{3,2}
at each p-adic level k, tracking how the survival set shrinks.
"""

from typing import Dict, List, Set


def ternary_digits(n: int, k: int) -> List[int]:
    """Return the k least-significant ternary digits of n (LSB first)."""
    digits = []
    for _ in range(k):
        digits.append(n % 3)
        n //= 3
    return digits


def is_cantor(n: int, k: int) -> bool:
    """Check if n's k least-significant ternary digits are all in {0, 1}."""
    return all(d in (0, 1) for d in ternary_digits(n, k))


def cantor_residues(k: int) -> List[int]:
    """Return all r in [0, 3^k) with ternary digits in {0, 1}."""
    # 2^k residues, generated by iterating over all binary strings of length k
    residues = []
    for mask in range(1 << k):
        r = 0
        power = 1
        for i in range(k):
            if mask & (1 << i):
                r += power
            power *= 3
        residues.append(r)
    return sorted(residues)


def cantor_units(k: int) -> List[int]:
    """Return Cantor residues mod 3^k that are units (not divisible by 3)."""
    return [r for r in cantor_residues(k) if r % 3 != 0]


def order_of_2_mod_3k(k: int) -> int:
    """Return the order of 2 mod 3^k, which is u_k = 2 * 3^(k-1)."""
    return 2 * (3 ** (k - 1))


def orbit_cantor_intersection(k: int) -> Set[int]:
    """Return {n mod u_k : 2^n mod 3^k ∈ C_k ∩ (Z/3^k Z)^×}.

    These are the n (mod u_k) for which 2^n is Cantor in the last k ternary digits.
    """
    mod = 3 ** k
    uk = order_of_2_mod_3k(k)
    cantor_set = set(cantor_units(k))
    result = set()
    power = 1  # 2^0 = 1
    for n in range(uk):
        if power in cantor_set:
            result.add(n)
        power = (power * 2) % mod
    return result


def survival_set(k_max: int) -> Dict[int, Set[int]]:
    """Compute S_k = {n in [0, u_k) : 2^n is Cantor mod 3^k}, for k = 1..k_max.

    Returns dict: {k: set of n}.

    KEY FINDING: S_k = N_k for all k. This is because if 2^n has no digit 2
    in its last k ternary digits, it automatically has no digit 2 in its last
    j digits for j < k. The survival set never shrinks.

    This means the Erdős conjecture (full ternary expansion of 2^n has no digit 2)
    is NOT captured by checking only the last k digits. The full expansion check
    requires examining all digits, not just the last k.
    """
    return {k: orbit_cantor_intersection(k) for k in range(1, k_max + 1)}


def full_ternary_cantor_check(n_max: int) -> List[int]:
    """Check which n in [0, n_max] have 2^n with ALL ternary digits in {0, 1}.

    This is the correct check for the Erdős conjecture: the FULL ternary
    expansion (not just the last k digits) must have no digit 2.

    Returns the list of n values satisfying the condition.
    """
    survivors = []
    for n in range(n_max + 1):
        val = 2 ** n
        # Check ALL ternary digits
        has_digit_2 = False
        temp = val
        while temp > 0:
            if temp % 3 == 2:
                has_digit_2 = True
                break
            temp //= 3
        if not has_digit_2:
            survivors.append(n)
    return survivors


def analyze_cantor_unit_structure(k_max: int = 10):
    """Analyze the algebraic structure of Cantor units mod 3^k."""
    print("\n=== Cantor Unit Structure ===")
    for k in range(1, k_max + 1):
        units = cantor_units(k)
        mod = 3 ** k
        unit_set = set(units)
        is_subgroup = True
        for a in units:
            for b in units:
                if (a * b) % mod not in unit_set:
                    is_subgroup = False
                    break
            if not is_subgroup:
                break
        print(f"k={k}: |C_k units|={len(units)}, subgroup under ×? {is_subgroup}")


def analyze_orbit_pattern(k_max: int = 15):
    """Analyze how the orbit maps to Cantor residues."""
    print("\n=== Orbit-Cantor Mapping Pattern ===")
    for k in range(1, min(k_max + 1, 8)):
        uk = order_of_2_mod_3k(k)
        mod = 3 ** k
        intersection = orbit_cantor_intersection(k)
        print(f"\nk={k} (u_k={uk}, mod={mod}):")
        for n in sorted(intersection):
            residue = pow(2, n, mod)
            digits = ternary_digits(residue, k)
            print(f"  n={n:>3}: 2^{n} mod {mod} = {residue:>3} = {''.join(str(d) for d in reversed(digits))}_3")


def analyze_2_to_n_ternary(k_max: int = 10):
    """Show the full ternary expansion of 2^n for n in {0, 2, 8}."""
    print("\n=== 2^n Ternary Expansions ===")
    for n in [0, 2, 8]:
        val = 2 ** n
        digits = []
        temp = val
        while temp > 0:
            digits.append(temp % 3)
            temp //= 3
        digits_str = ''.join(str(d) for d in reversed(digits))
        has_two = 2 in digits
        print(f"2^{n} = {val} = {digits_str}_3 (has digit 2: {has_two})")


def cross_level_consistency(k_max: int = 15):
    """Check that the projection of N_k mod u_j is contained in N_j for j < k.

    This is the correct containment: if 2^n has no digit 2 in its last k
    ternary digits, then 2^n has no digit 2 in its last j digits (for j < k).
    This holds trivially because the last j digits are a prefix of the last k.
    """
    print("\n=== Cross-Level Consistency ===")
    surv = survival_set(k_max)
    all_consistent = True
    for k in range(2, k_max + 1):
        s_k = surv[k]
        uk = order_of_2_mod_3k(k)
        consistent_here = True
        for j in range(1, k):
            s_j = surv[j]
            uj = order_of_2_mod_3k(j)
            projected = set(n % uj for n in s_k)
            consistent_j = projected.issubset(s_j)
            consistent_here = consistent_here and consistent_j
        all_consistent = all_consistent and consistent_here
        print(f"k={k}: projection to all lower levels consistent? {consistent_here}  (|N_k|={len(s_k)}, u_k={uk})")
    print(f"\nAll levels consistent (projection of N_k ⊆ N_j for all j < k): {all_consistent}")


def print_survival_analysis(k_max: int = 15):
    """Print the survival set analysis table.

    Note: S_k = N_k for all k (trivially). The |S_k| column equals |N_k|.
    """
    surv = survival_set(k_max)
    print(f"{'k':>3} {'u_k':>12} {'|N_k|=|S_k|':>12} {'ratio':>10} {'N_k content'}")
    print("-" * 80)
    for k in range(1, k_max + 1):
        uk = order_of_2_mod_3k(k)
        n_k = surv[k]  # S_k = N_k
        n_k_count = len(n_k)
        ratio = n_k_count / uk if uk > 0 else 0
        content = sorted(n_k)
        if len(content) > 10:
            content_str = f"{{{content[0]}, ..., {content[-1]}}} ({len(content)} elements)"
        else:
            content_str = str(content)
        print(f"{k:>3} {uk:>12} {n_k_count:>12} {ratio:>10.4f} {content_str}")


if __name__ == "__main__":
    K_MAX = 15

    print(f"p-Adic Orbit-Cantor Intersection Analysis (k = 1..{K_MAX})")
    print("=" * 70)

    # Core analysis
    print_survival_analysis(K_MAX)

    # Structural analysis
    analyze_cantor_unit_structure(min(K_MAX, 8))
    analyze_orbit_pattern(min(K_MAX, 8))
    analyze_2_to_n_ternary()
    cross_level_consistency(K_MAX)

    # Key result: full ternary check confirms {0, 2, 8}
    print(f"\n=== Key Result ===")
    print("The survival set S_k = N_k (last-k-digits check) never shrinks,")
    print("so examining only finitely many ternary digits cannot decide the")
    print("Erdős conjecture. Instead, we check the FULL ternary expansion.\n")

    full_check = full_ternary_cantor_check(100_000)
    print(f"full_ternary_cantor_check(100000) = {full_check}")
    print(f"These are the n ≤ 100000 where ALL ternary digits of 2^n are in {{0, 1}}.")

    surv = survival_set(K_MAX)
    s_final = surv[K_MAX]
    print(f"\nS_{K_MAX} (last-{K_MAX}-digit survival set) has {len(s_final)} elements,")
    print("but only {0, 2, 8} satisfy the FULL ternary condition (digit 2 absent everywhere).")

    if full_check == [0, 2, 8]:
        print("\nCONFIRMED: The full ternary check identifies exactly {0, 2, 8} up to n = 100000.")
    else:
        print(f"\nNOTE: Additional survivors found in full check: {full_check}")
