/-
  Bridge Theorem: Ostrowski Coefficient Analysis

  Documents the structural reason why the bridge theorem holds.
  Computational verification for K=5..15 confirms all r in N_K \ {0,2,8}
  have digit 2 in first 30 ternary digits of 2^r.

  Reference: verify_middle/ostrowski_bridge_deep.py
  Reference: verify_middle/ostrowski_pattern_analysis.py
-/

import Mathlib.Tactic
import ErdosTernary.BridgeCompute
import ErdosTernary.BridgeComputeExtended
import ErdosTernary.BridgeUniform

open ErdosTernary.BridgeCompute
open ErdosTernary.BridgeComputeExtended
open ErdosTernary.BridgeUniform
open Narkiewicz

namespace ErdosTernary.BridgeOstrowski

/-! ## Computational Evidence for K=5..15

  The deep analysis (ostrowski_bridge_deep.py) verifies:
  - For K=5: 13 residues checked, all have digit 2 in first 30 digits
  - For K=6: 29 residues checked, all have digit 2 in first 30 digits
  - For K=7: 61 residues checked, all have digit 2 in first 30 digits
  - For K=8: 125 residues checked, all have digit 2 in first 30 digits
  - For K=9: 253 residues checked, all have digit 2 in first 30 digits
  - For K=10: 509 residues checked, all have digit 2 in first 30 digits
  - For K=11: 1021 residues checked, all have digit 2 in first 30 digits
  - For K=12: 2045 residues checked, all have digit 2 in first 30 digits
  - For K=13: 4093 residues checked, all have digit 2 in first 30 digits
  - For K=14: 8189 residues checked, all have digit 2 in first 30 digits
  - For K=15: 16381 residues checked, all have digit 2 in first 30 digits

  The max first digit-2 position is ~23, well within the 30-digit window.
  The mean first digit-2 position is ~2, showing most residues have digit 2 early.
-/

/-- The bridge theorem holds for K=5..9 by native_decide. -/
theorem bridge_ostrowski_K5_K9 :
    ∀ K ∈ ({5, 6, 7, 8, 9} : Finset Nat),
    ∀ r ∈ computeNK K, r ∉ ({0, 2, 8} : Finset Nat) →
    ¬(memCantorNat (2 ^ r)) := by
  intro K hK r hr hs
  fin_cases hK
  all_goals simp only [Finset.mem_insert, Finset.mem_singleton] at hs
  all_goals have hn0 : r ≠ 0 := by omega
  all_goals have hn2 : r ≠ 2 := by omega
  all_goals have hn8 : r ≠ 8 := by omega
  · exact bridge_first_period_all 5 (by omega) r hr ⟨hn0, hn2, hn8⟩
  · exact bridge_first_period_all 6 (by omega) r hr ⟨hn0, hn2, hn8⟩
  · exact bridge_first_period_all 7 (by omega) r hr ⟨hn0, hn2, hn8⟩
  · exact bridge_first_period_all 8 (by omega) r hr ⟨hn0, hn2, hn8⟩
  · exact bridge_first_period_all 9 (by omega) r hr ⟨hn0, hn2, hn8⟩

/-! ## Key Structural Insights

  From the Ostrowski analysis:

  1. Position 0 is always 0 (all N_K elements are < q_1 = 1)
  2. Position 9 is highly active (~94% non-zero for K>=10)
  3. Most residues have max coefficient >= 2 (tree structure from Saye recursion)
  4. First digit-2 position is bounded by ~23 for K<=15

  The bridge theorem works because N_K elements have constrained Ostrowski
  representations (generated by Saye recursion) that force {r*a} to avoid
  the thin Cantor set C_30.
-/

end ErdosTernary.BridgeOstrowski
